name = "strith"
version = "1.2.0"
license = "license"
author = "Tomohiro Degawa"
maintainer = "degawa.tomohiro@gmail.com"
copyright = "Copyright 2023, Tomohiro Degawa"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = true
